spring:
  jackson:
    mapper:
      use-std-bean-naming: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      path: /api/db
      enabled: true
  datasource:
    url: jdbc:h2:file:./spring-angular-starter-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:  jpa:    open-in-view: false
    hibernate:      ddl-auto: update

example:
  enable-sleep: true